name: lab_registration_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: ^2.0.3
  provider: ^6.0.2
  flutter_svg: ^1.0.0
  google_fonts:
  intl: ^0.17.0
  eva_icons_flutter: ^3.0.2
  flutter_iconly: ^1.0.2
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  dio: ^4.0.4
  snippet_coder_utils: ^1.0.9
  api_cache_manager: ^1.0.2
  flutter_easyloading: ^3.0.3
  syncfusion_flutter_calendar: ^19.4.43
  syncfusion_flutter_xlsio: ^19.4.48-beta
  syncfusion_flutter_datagrid: ^19.4.50
  path_provider: ^2.0.8
  open_file: ^3.2.1
  universal_html: ^2.0.8
  url_strategy: ^0.2.0
  rolling_switch: ^0.0.2
  animated_splash_screen: ^1.2.0
  file_picker: ^4.5.1
  lottie: ^1.2.2
  badges: ^2.0.2
  flutter_downloader: ^1.7.3
  permission_handler: ^9.2.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

flutter:
  assets:
    - assets/images/raster/
    - assets/images/vector/
    - assets/lotties/
  uses-material-design: true

